
title: Sumit Suman | Resume 
url: 'https://sumitsuman.com'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Sumit Suman
tagline: Resume
pic: sumit_profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
#email: sumitsuman+r@gmail.com
#website: sumitsuman.com #do not add http://
email: sumitsuman.pro+resume@gmail.com
linkedin: sumitsuman
#github: sumitsuman
twitter: '@anothersumit'


# Tracker
analytics: 
#Update all the sections by editing the files inside _includes folder.
